### ISSUE TITLE
suggestion: increase clarity on cross sections in task 1

### ISSUE THREAD

**Issue by py1sl** [fusion-energy/neutronics-workshop#11]
In task 1 it would perhaps be useful to be clear in the text when plotting microscopic cross section or macroscopic cross section, Depending on the target audience it might be worth adding the definitions & relationship between them to the text.  

The doppler broadening plotting function looks to be doing things differently i.e. reading a data file directly and not calling openmc.calculate_cexs() and unlike the other functions will not take a list of isotopes or elements. calculate_cexs() does quite a few checks and processing steps - does this mean it is not sensible to compare standard temperature data from plot isotope function with the same temperature in the doppler broadening function.

**Comment by Shimwell** [comment]
Doppler broadening section uses a WMP technique and is generated on the fly instead of simply looking up the cross  section.

You can compare WMP Doppler broaden cross sections with non broaden cross sections on the same axis. Perhaps best to use ENDF B VII.I as that is where the data comes from originally

https://github.com/mit-crpg/WMP_Library

**Comment by Shimwell** [comment]
For the Microscopic and Macroscopic suggestion I've put in PR #12 

Thanks for raising this issue @py1sl

**Comment by Shimwell** [comment]
solved by #12
