### ISSUE TITLE
task-3 part 1 plots not showing due to color_by='material'

### ISSUE THREAD

**Issue by py1sl** [fusion-energy/neutronics-workshop#239]
The initial plots do not show up in the notebook as they are set to "color_by='material'",  but no material is set until the last code block.

removing color_by='material' from the plt.show line solves this issue

**Comment by shimwell** [comment]
thanks py1sl I think I just fixed this one and merged it into the main branch

also I made some changes to openmc so that we no longer have to do universe.plot or geometry.root_universe.plot and now have access to the plot on the geometry object. So I fixed the material thing while updating to make use of the latest openmc api
